COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False
development:
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}

production:
 SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}